version: '3.8'
services:
  # Postgres
  dental_postgres_db:
    container_name: dental_postgres_db
    image: postgres:latest
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

  # Streamlit App
  dental_streamlit_app:
    container_name: dental_streamlit_app
    build: ./streamlit_app
    ports:
      - '8501:8501'
    restart: on-failure
